### ISSUE TITLE
Remove Terraform env duplications

### ISSUE THREAD

**Issue by volovyks** [near/mpc-recovery#566]
### Description
We have many environments; each has its folder and a set of files. They are identical or almost identical. 
With this approach, updating Terraform configs requires changes in all these duplications.
Example PR: https://github.com/near/mpc-recovery/pull/565
cc @ppca

**Comment by kmaus-near** [comment]
What is the status of MPC (instances on cloud run) services? Does multichain do the job of the cloudrun MPC nodes?  or are MPC nodes still being used? The reason I ask is because if those environments aren't utilized anymore, I can clean up both the terraform and resources.

If the cloudrun instances are still being used, perhaps we can identify which ones are not needed by directory so I can remove them if possible.

**Comment by volovyks** [comment]
@kmaus-near I believe you removed all the redundant configs and envs. Please, try to reduce config duplication if possible. But if you will hit the wall with it - feel free to close this issue.

**Comment by kmaus-near** [comment]
I believe this was closed by #600. As far as duplication, I think we should keep what we have for multichain separate by environment. Feel free to add annoying variable changes to the tfvars files in dev.
