### ISSUE TITLE
v5 error: Signature was not provided in time.

### ISSUE THREAD

**Issue by mikedotexe** [near/mpc-recovery#591]
## Description

I'm trying to find a deployment contract to complete a task with UTXOs, and saw on Telegram there's `v5.multichain-mpc-dev.testnet`, so I pointed there.

>Smart contract panicked: Signature was not provided in time. Please, try again.

https://testnet.nearblocks.io/txns/FjuRmgXDEmVFfoVt7zqM9guHhotoutAaxxcU3asaVkAL

**Comment by mikedotexe** [comment]
Seeing it again today, fyi

**Comment by volovyks** [comment]
This issue is very generic. MPC can fail to provide a signature in time for 1,000,000 different reasons. We are tracking the success rate in Grafana, here is the data for the last 7 days:
<img width="745" alt="image" src="https://github.com/near/mpc-recovery/assets/4030422/ef60c321-5569-41c8-98eb-5bf386714396">

Also, we are setting up alerts and an on-call schedule to keep an eye on this and other metrics.

Developers should retry in case of a failure. If this situation is consistent - please, reopen this issue and we will take a closer look.
